### ISSUE TITLE
what are the latest technical skills you have used in this project?

### ISSUE THREAD

**Issue by ranisudir** [nicothin/web-development#17]
HTML/CSS
JAVASCRIPT/JQUERY ?

also do visit to learn more about [web development ](https://www.clariwell.in/best-web-development-courses-in-pune)

**Comment by liteCarma** [comment]
🤭

**Comment by nicothin** [comment]
damn bot

**Comment by DevanshKarnani** [comment]
Learn more about this at https://www.clariwell.in/best-java-course-in-pune
