### ISSUE TITLE
Ошибка в тексте 

### ISSUE THREAD

**Issue by cognoscentis** [nicothin/web-development#6]
В readme.md в папке bash 

> Работая с _**кольнолью**_, мы всегда «находимся» в какой-то папке (это указано в строке над курсором). Если там написано ~, то мы в папке пользователя (зависит от настроек Windows, чаще всего это C:/Users/ВАШЕИМЯПОЛЬЗОВАТЕЛЯ/), если там /d/projects, мы в папке D:/projects.

**Comment by nicothin** [comment]
https://github.com/nicothin/web-development/commit/288a5a76358ca6ce0a1053a37d33d2eeb009ca31
